# VERSION 1.0

FROM ubuntu
MAINTAINER Jianshen Liu <jliu120@ucsc.edu>

RUN sudo apt-get install -y software-properties-common

# Install Oracle Java 8
RUN sudo add-apt-repository ppa:webupd8team/java
RUN sudo apt-get update
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN sudo apt-get install -y oracle-java8-set-default

# Install Python2
RUN sudo apt-get install -y python

# Install VIM
RUN sudo apt-get install -y vim

RUN mkdir /root/softwares
WORKDIR /root/softwares

# Install Apache Maven 3.3.9
RUN wget http://mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN tar xzvf apache-maven-3.3.9-bin.tar.gz
RUN rm apache-maven-3.3.9-bin.tar.gz
ENV PATH /root/softwares/apache-maven-3.3.9/bin:$PATH

# Install Apache Ant 1.9.6
RUN wget http://apache.go-parts.com//ant/binaries/apache-ant-1.9.6-bin.tar.gz
RUN tar xzvf apache-ant-1.9.6-bin.tar.gz
RUN rm apache-ant-1.9.6-bin.tar.gz
ENV PATH /root/softwares/apache-ant-1.9.6/bin:$PATH

# Install screen
RUN sudo apt-get install -y screen
COPY .screenrc /root

#Install Git
RUN sudo apt-get install -y git

EXPOSE 80 8000-9000

WORKDIR /root
